# Generated by Django 3.1.3 on 2020-12-13 06:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 12, 13, 6, 5, 11, 887613, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
